// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdnzbnlxpwyndhtygoez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkbnpibmx4cHd5bmRodHlnb2V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MzQyMjgsImV4cCI6MjA1NDExMDIyOH0.5AB3zpsFWS-FJuzUUHnUbjiTWxAvqnxgu4Ng3pVDMic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);